# coding: utf-8
"""
    Account Information API

    In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 

    The version of the OpenAPI document: 3.1.11
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from hsbc_account_information_ce_python_sdk.client_custom import ClientCustom
from hsbc_account_information_ce_python_sdk.configuration import Configuration
from hsbc_account_information_ce_python_sdk.api_client import ApiClient
from hsbc_account_information_ce_python_sdk.type_util import copy_signature
from hsbc_account_information_ce_python_sdk.apis.tags.account_access_consents_api import AccountAccessConsentsApi
from hsbc_account_information_ce_python_sdk.apis.tags.accounts_api import AccountsApi
from hsbc_account_information_ce_python_sdk.apis.tags.balances_api import BalancesApi
from hsbc_account_information_ce_python_sdk.apis.tags.beneficiaries_api import BeneficiariesApi
from hsbc_account_information_ce_python_sdk.apis.tags.direct_debits_api import DirectDebitsApi
from hsbc_account_information_ce_python_sdk.apis.tags.parties_api import PartiesApi
from hsbc_account_information_ce_python_sdk.apis.tags.products_api import ProductsApi
from hsbc_account_information_ce_python_sdk.apis.tags.scheduled_payments_api import ScheduledPaymentsApi
from hsbc_account_information_ce_python_sdk.apis.tags.standing_orders_api import StandingOrdersApi
from hsbc_account_information_ce_python_sdk.apis.tags.transactions_api import TransactionsApi



class HsbcAccountInformationCe(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.account_access_consents: AccountAccessConsentsApi = AccountAccessConsentsApi(api_client)
        self.accounts: AccountsApi = AccountsApi(api_client)
        self.balances: BalancesApi = BalancesApi(api_client)
        self.beneficiaries: BeneficiariesApi = BeneficiariesApi(api_client)
        self.direct_debits: DirectDebitsApi = DirectDebitsApi(api_client)
        self.parties: PartiesApi = PartiesApi(api_client)
        self.products: ProductsApi = ProductsApi(api_client)
        self.scheduled_payments: ScheduledPaymentsApi = ScheduledPaymentsApi(api_client)
        self.standing_orders: StandingOrdersApi = StandingOrdersApi(api_client)
        self.transactions: TransactionsApi = TransactionsApi(api_client)
