# coding: utf-8

"""
    Account Information API

    In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 

    The version of the OpenAPI document: 3.1.11
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from hsbc_account_information_ce_python_sdk.pydantic.ob_currency_exchange5_instructed_amount import OBCurrencyExchange5InstructedAmount

class OBCurrencyExchange5(BaseModel):
    # Currency from which an amount is to be converted in a currency conversion.
    source_currency: str = Field(alias='SourceCurrency')

    # Factor used to convert an amount from one currency into another. This reflects the price at which one currency was bought with another currency. Usage: ExchangeRate expresses the ratio between UnitCurrency and QuotedCurrency (ExchangeRate = UnitCurrency/QuotedCurrency).
    exchange_rate: typing.Union[int, float] = Field(alias='ExchangeRate')

    # Currency into which an amount is to be converted in a currency conversion.
    target_currency: typing.Optional[str] = Field(None, alias='TargetCurrency')

    # Currency in which the rate of exchange is expressed in a currency exchange. In the example 1GBP = xxxCUR, the unit currency is GBP.
    unit_currency: typing.Optional[str] = Field(None, alias='UnitCurrency')

    # Unique identification to unambiguously identify the foreign exchange contract.
    contract_identification: typing.Optional[str] = Field(None, alias='ContractIdentification')

    # Date and time at which an exchange rate is quoted.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
    quotation_date: typing.Optional[datetime] = Field(None, alias='QuotationDate')

    instructed_amount: typing.Optional[OBCurrencyExchange5InstructedAmount] = Field(None, alias='InstructedAmount')
    class Config:
        arbitrary_types_allowed = True
