# coding: utf-8

"""
    Account Information API

    In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 

    The version of the OpenAPI document: 3.1.11
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class OBError1(BaseModel):
    # Low level textual error code, e.g., UK.OBIE.Field.Missing
    error_code: Literal["UK.OBIE.Field.Expected", "UK.OBIE.Field.Invalid", "UK.OBIE.Field.InvalidDate", "UK.OBIE.Field.Missing", "UK.OBIE.Field.Unexpected", "UK.OBIE.Header.Invalid", "UK.OBIE.Header.Missing", "UK.OBIE.Reauthenticate", "UK.OBIE.Resource.ConsentMismatch", "UK.OBIE.Resource.InvalidConsentStatus", "UK.OBIE.Resource.InvalidFormat", "UK.OBIE.Resource.NotFound", "UK.OBIE.Rules.AfterCutOffDateTime", "UK.OBIE.Rules.DuplicateReference", "UK.OBIE.Signature.Invalid", "UK.OBIE.Signature.InvalidClaim", "UK.OBIE.Signature.Malformed", "UK.OBIE.Signature.Missing", "UK.OBIE.Signature.MissingClaim", "UK.OBIE.Signature.Unexpected", "UK.OBIE.UnexpectedError", "UK.OBIE.Unsupported.AccountIdentifier", "UK.OBIE.Unsupported.AccountSecondaryIdentifier", "UK.OBIE.Unsupported.Currency", "UK.OBIE.Unsupported.Frequency", "UK.OBIE.Unsupported.LocalInstrument", "UK.OBIE.Unsupported.Scheme"] = Field(alias='ErrorCode')

    # A description of the error that occurred. e.g., 'A mandatory field isn't supplied' or 'RequestedExecutionDateTime must be in future' OBIE doesn't standardise this field
    message: str = Field(alias='Message')

    # Recommended but optional reference to the JSON Path of the field with error, e.g., Data.Initiation.InstructedAmount.Currency
    path: typing.Optional[str] = Field(None, alias='Path')

    # URL to help remediate the problem, or provide more information, or to API Reference, or help etc
    url: typing.Optional[str] = Field(None, alias='Url')
    class Config:
        arbitrary_types_allowed = True
