# coding: utf-8

"""
    Account Information API

    In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 

    The version of the OpenAPI document: 3.1.11
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from hsbc_account_information_ce_python_sdk.pydantic.account_id import AccountId
from hsbc_account_information_ce_python_sdk.pydantic.ob_read_offer1_data_offer_item_amount import OBReadOffer1DataOfferItemAmount
from hsbc_account_information_ce_python_sdk.pydantic.ob_read_offer1_data_offer_item_fee import OBReadOffer1DataOfferItemFee

class OBReadOffer1DataOfferItem(BaseModel):
    account_id: AccountId = Field(alias='AccountId')

    # A unique and immutable identifier used to identify the offer resource. This identifier has no meaning to the account owner.
    offer_id: typing.Optional[str] = Field(None, alias='OfferId')

    # Offer type, in a coded form.
    offer_type: typing.Optional[Literal["BalanceTransfer", "LimitIncrease", "MoneyTransfer", "Other", "PromotionalRate"]] = Field(None, alias='OfferType')

    # Further details of the offer.
    description: typing.Optional[str] = Field(None, alias='Description')

    # Date and time at which the offer starts.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
    start_date_time: typing.Optional[datetime] = Field(None, alias='StartDateTime')

    # Date and time at which the offer ends.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
    end_date_time: typing.Optional[datetime] = Field(None, alias='EndDateTime')

    # Rate associated with the offer type.
    rate: typing.Optional[str] = Field(None, alias='Rate')

    # Value associated with the offer type.
    value: typing.Optional[int] = Field(None, alias='Value')

    # Further details of the term of the offer.
    term: typing.Optional[str] = Field(None, alias='Term')

    # URL (Uniform Resource Locator) where documentation on the offer can be found
    u_r_l: typing.Optional[str] = Field(None, alias='URL')

    amount: typing.Optional[OBReadOffer1DataOfferItemAmount] = Field(None, alias='Amount')

    fee: typing.Optional[OBReadOffer1DataOfferItemFee] = Field(None, alias='Fee')
    class Config:
        arbitrary_types_allowed = True
