# coding: utf-8

"""
    Account Information API

    In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 

    The version of the OpenAPI document: 3.1.11
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from hsbc_account_information_ce_python_sdk.pydantic.account_id import AccountId
from hsbc_account_information_ce_python_sdk.pydantic.ob_external_statement_type1_code import OBExternalStatementType1Code
from hsbc_account_information_ce_python_sdk.pydantic.ob_statement2_basic_statement_benefit import OBStatement2BasicStatementBenefit
from hsbc_account_information_ce_python_sdk.pydantic.ob_statement2_basic_statement_date_time import OBStatement2BasicStatementDateTime
from hsbc_account_information_ce_python_sdk.pydantic.ob_statement2_basic_statement_description import OBStatement2BasicStatementDescription
from hsbc_account_information_ce_python_sdk.pydantic.ob_statement2_basic_statement_fee import OBStatement2BasicStatementFee
from hsbc_account_information_ce_python_sdk.pydantic.ob_statement2_basic_statement_interest import OBStatement2BasicStatementInterest
from hsbc_account_information_ce_python_sdk.pydantic.ob_statement2_basic_statement_rate import OBStatement2BasicStatementRate
from hsbc_account_information_ce_python_sdk.pydantic.ob_statement2_basic_statement_value import OBStatement2BasicStatementValue
from hsbc_account_information_ce_python_sdk.pydantic.statement_id import StatementId
from hsbc_account_information_ce_python_sdk.pydantic.statement_reference import StatementReference

class OBStatement2Basic(BaseModel):
    account_id: AccountId = Field(alias='AccountId')

    type: OBExternalStatementType1Code = Field(alias='Type')

    # Date and time at which the statement period starts.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
    start_date_time: datetime = Field(alias='StartDateTime')

    # Date and time at which the statement period ends.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
    end_date_time: datetime = Field(alias='EndDateTime')

    # Date and time at which the resource was created.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
    creation_date_time: datetime = Field(alias='CreationDateTime')

    statement_id: typing.Optional[StatementId] = Field(None, alias='StatementId')

    statement_reference: typing.Optional[StatementReference] = Field(None, alias='StatementReference')

    statement_description: typing.Optional[OBStatement2BasicStatementDescription] = Field(None, alias='StatementDescription')

    statement_benefit: typing.Optional[OBStatement2BasicStatementBenefit] = Field(None, alias='StatementBenefit')

    statement_fee: typing.Optional[OBStatement2BasicStatementFee] = Field(None, alias='StatementFee')

    statement_interest: typing.Optional[OBStatement2BasicStatementInterest] = Field(None, alias='StatementInterest')

    statement_date_time: typing.Optional[OBStatement2BasicStatementDateTime] = Field(None, alias='StatementDateTime')

    statement_rate: typing.Optional[OBStatement2BasicStatementRate] = Field(None, alias='StatementRate')

    statement_value: typing.Optional[OBStatement2BasicStatementValue] = Field(None, alias='StatementValue')
    class Config:
        arbitrary_types_allowed = True
