# coding: utf-8

"""
    Account Information API

    In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 

    The version of the OpenAPI document: 3.1.11
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from hsbc_account_information_ce_python_sdk.pydantic.obbca_data1_credit_interest_tier_band_set_item_notes import OBBCAData1CreditInterestTierBandSetItemNotes
from hsbc_account_information_ce_python_sdk.pydantic.obbca_data1_credit_interest_tier_band_set_item_tier_band import OBBCAData1CreditInterestTierBandSetItemTierBand

class OBBCAData1CreditInterestTierBandSetItem(BaseModel):
    # The methodology of how credit interest is paid/applied. It can be:-  1. Banded Interest rates are banded. i.e. Increasing rate on whole balance as balance increases.  2. Tiered Interest rates are tiered. i.e. increasing rate for each tier as balance increases, but interest paid on tier fixed for that tier and not on whole balance.  3. Whole The same interest rate is applied irrespective of the BCA balance
    tier_band_method: Literal["Banded", "Tiered", "Whole"] = Field(alias='TierBandMethod')

    # Describes whether accrued interest is payable only to the BCA or to another bank account
    destination: Literal["PayAway", "SelfCredit"] = Field(alias='Destination')

    tier_band: OBBCAData1CreditInterestTierBandSetItemTierBand = Field(alias='TierBand')

    # Methods of calculating interest
    calculation_method: typing.Optional[Literal["Compound", "SimpleInterest"]] = Field(None, alias='CalculationMethod')

    notes: typing.Optional[OBBCAData1CreditInterestTierBandSetItemNotes] = Field(None, alias='Notes')
    class Config:
        arbitrary_types_allowed = True
