# coding: utf-8

"""
    Account Information API

    In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 

    The version of the OpenAPI document: 3.1.11
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from hsbc_account_information_ce_python_sdk.pydantic.obpca_data1_overdraft_overdraft_tier_band_set_item_overdraft_tier_band_item_notes import OBPCAData1OverdraftOverdraftTierBandSetItemOverdraftTierBandItemNotes
from hsbc_account_information_ce_python_sdk.pydantic.obpca_data1_overdraft_overdraft_tier_band_set_item_overdraft_tier_band_item_overdraft_fees_charges import OBPCAData1OverdraftOverdraftTierBandSetItemOverdraftTierBandItemOverdraftFeesCharges

class OBPCAData1OverdraftOverdraftTierBandSetItemOverdraftTierBandItem(BaseModel):
    # Minimum value of Overdraft Tier/Band
    tier_value_min: str = Field(alias='TierValueMin')

    # Unique and unambiguous identification of a  Tier Band for a overdraft.
    identification: typing.Optional[str] = Field(None, alias='Identification')

    # Maximum value of Overdraft Tier/Band
    tier_value_max: typing.Optional[str] = Field(None, alias='TierValueMax')

    # Interest charged on whole amount or tiered/banded
    overdraft_interest_charging_coverage: typing.Optional[Literal["Tiered", "Whole"]] = Field(None, alias='OverdraftInterestChargingCoverage')

    # Indicates that a bank provides the overdraft limit up to TierValueMIn to all customers automatically
    bank_guaranteed_indicator: typing.Optional[bool] = Field(None, alias='BankGuaranteedIndicator')

    # EAR means Effective Annual Rate and/or Equivalent Annual Rate (frequently used interchangeably), being the actual annual interest rate of an Overdraft.
    e_a_r: typing.Optional[str] = Field(None, alias='EAR')

    # An annual percentage rate (APR) is the annual rate charged for borrowing or earned through an investment. APR is expressed as a percentage that represents the actual yearly cost of funds over the term of a loan. This includes any fees or additional costs associated with the transaction but does not take compounding into account.
    representative_a_p_r: typing.Optional[str] = Field(None, alias='RepresentativeAPR')

    notes: typing.Optional[OBPCAData1OverdraftOverdraftTierBandSetItemOverdraftTierBandItemNotes] = Field(None, alias='Notes')

    overdraft_fees_charges: typing.Optional[OBPCAData1OverdraftOverdraftTierBandSetItemOverdraftTierBandItemOverdraftFeesCharges] = Field(None, alias='OverdraftFeesCharges')
    class Config:
        arbitrary_types_allowed = True
