# coding: utf-8

"""
    Account Information API

    In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 

    The version of the OpenAPI document: 3.1.11
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hsbc_account_information_ce_python_sdk.type.account_id import AccountId
from hsbc_account_information_ce_python_sdk.type.beneficiary_id import BeneficiaryId
from hsbc_account_information_ce_python_sdk.type.ob_beneficiary_type1_code import OBBeneficiaryType1Code
from hsbc_account_information_ce_python_sdk.type.ob_branch_and_financial_institution_identification60 import OBBranchAndFinancialInstitutionIdentification60
from hsbc_account_information_ce_python_sdk.type.ob_cash_account50 import OBCashAccount50
from hsbc_account_information_ce_python_sdk.type.ob_supplementary_data1 import OBSupplementaryData1
from hsbc_account_information_ce_python_sdk.type.reference import Reference

class RequiredOBBeneficiary5Detail(TypedDict):
    CreditorAccount: OBCashAccount50

class OptionalOBBeneficiary5Detail(TypedDict, total=False):
    AccountId: AccountId

    BeneficiaryId: BeneficiaryId

    BeneficiaryType: OBBeneficiaryType1Code

    Reference: Reference

    SupplementaryData: OBSupplementaryData1

    CreditorAgent: OBBranchAndFinancialInstitutionIdentification60

class OBBeneficiary5Detail(RequiredOBBeneficiary5Detail, OptionalOBBeneficiary5Detail):
    pass
