# coding: utf-8

"""
    Account Information API

    In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 

    The version of the OpenAPI document: 3.1.11
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hsbc_account_information_ce_python_sdk.type.ob_interest_calculation_method1_code import OBInterestCalculationMethod1Code
from hsbc_account_information_ce_python_sdk.type.ob_other_code_type10 import OBOtherCodeType10
from hsbc_account_information_ce_python_sdk.type.ob_read_product2_data_product_item_other_product_type_credit_interest_tier_band_set_item_notes import OBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItemNotes
from hsbc_account_information_ce_python_sdk.type.ob_read_product2_data_product_item_other_product_type_credit_interest_tier_band_set_item_tier_band import OBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItemTierBand

class RequiredOBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItem(TypedDict):
    # The methodology of how credit interest is paid/applied. It can be:- 1. Banded Interest rates are banded. i.e. Increasing rate on whole balance as balance increases. 2. Tiered Interest rates are tiered. i.e. increasing rate for each tier as balance increases, but interest paid on tier fixed for that tier and not on whole balance. 3. Whole The same interest rate is applied irrespective of the product holder's account balance
    TierBandMethod: str

    # Describes whether accrued interest is payable only to the BCA or to another bank account
    Destination: str

    TierBand: OBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItemTierBand

class OptionalOBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItem(TypedDict, total=False):
    CalculationMethod: OBInterestCalculationMethod1Code

    Notes: OBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItemNotes

    OtherCalculationMethod: OBOtherCodeType10

    OtherDestination: OBOtherCodeType10

class OBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItem(RequiredOBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItem, OptionalOBReadProduct2DataProductItemOtherProductTypeCreditInterestTierBandSetItem):
    pass
