# coding: utf-8

"""
    Account Information API

    In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 

    The version of the OpenAPI document: 3.1.11
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from hsbc_account_information_ce_python_sdk.type.account_id import AccountId
from hsbc_account_information_ce_python_sdk.type.frequency1 import Frequency1
from hsbc_account_information_ce_python_sdk.type.number_of_payments import NumberOfPayments
from hsbc_account_information_ce_python_sdk.type.ob_active_or_historic_currency_and_amount11 import OBActiveOrHistoricCurrencyAndAmount11
from hsbc_account_information_ce_python_sdk.type.ob_active_or_historic_currency_and_amount2 import OBActiveOrHistoricCurrencyAndAmount2
from hsbc_account_information_ce_python_sdk.type.ob_active_or_historic_currency_and_amount3 import OBActiveOrHistoricCurrencyAndAmount3
from hsbc_account_information_ce_python_sdk.type.ob_active_or_historic_currency_and_amount4 import OBActiveOrHistoricCurrencyAndAmount4
from hsbc_account_information_ce_python_sdk.type.ob_external_standing_order_status1_code import OBExternalStandingOrderStatus1Code
from hsbc_account_information_ce_python_sdk.type.ob_supplementary_data1 import OBSupplementaryData1
from hsbc_account_information_ce_python_sdk.type.reference import Reference
from hsbc_account_information_ce_python_sdk.type.standing_order_id import StandingOrderId

class RequiredOBStandingOrder6Basic(TypedDict):
    AccountId: AccountId

    Frequency: Frequency1

class OptionalOBStandingOrder6Basic(TypedDict, total=False):
    StandingOrderId: StandingOrderId

    Reference: Reference

    # The date on which the first payment for a Standing Order schedule will be made.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
    FirstPaymentDateTime: datetime

    # The date on which the next payment for a Standing Order schedule will be made.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
    NextPaymentDateTime: datetime

    # The date on which the last (most recent) payment for a Standing Order schedule was made.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
    LastPaymentDateTime: datetime

    # The date on which the final payment for a Standing Order schedule will be made.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
    FinalPaymentDateTime: datetime

    NumberOfPayments: NumberOfPayments

    StandingOrderStatusCode: OBExternalStandingOrderStatus1Code

    FirstPaymentAmount: OBActiveOrHistoricCurrencyAndAmount2

    NextPaymentAmount: OBActiveOrHistoricCurrencyAndAmount3

    LastPaymentAmount: OBActiveOrHistoricCurrencyAndAmount11

    FinalPaymentAmount: OBActiveOrHistoricCurrencyAndAmount4

    SupplementaryData: OBSupplementaryData1

class OBStandingOrder6Basic(RequiredOBStandingOrder6Basic, OptionalOBStandingOrder6Basic):
    pass
