# coding: utf-8

"""
    Account Information API

    In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 

    The version of the OpenAPI document: 3.1.11
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hsbc_account_information_ce_python_sdk import schemas  # noqa: F401


class Links(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Links relevant to the payload
    """


    class MetaOapg:
        required = {
            "Self",
        }
        
        class properties:
            _self = schemas.StrSchema
            First = schemas.StrSchema
            Prev = schemas.StrSchema
            Next = schemas.StrSchema
            Last = schemas.StrSchema
            __annotations__ = {
                "Self": _self,
                "First": First,
                "Prev": Prev,
                "Next": Next,
                "Last": Last,
            }
    
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Self"]) -> MetaOapg.properties._self: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["First"]) -> MetaOapg.properties.First: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Prev"]) -> MetaOapg.properties.Prev: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Next"]) -> MetaOapg.properties.Next: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Last"]) -> MetaOapg.properties.Last: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Self", "First", "Prev", "Next", "Last", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Self"]) -> MetaOapg.properties._self: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["First"]) -> typing.Union[MetaOapg.properties.First, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Prev"]) -> typing.Union[MetaOapg.properties.Prev, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Next"]) -> typing.Union[MetaOapg.properties.Next, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Last"]) -> typing.Union[MetaOapg.properties.Last, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Self", "First", "Prev", "Next", "Last", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        First: typing.Union[MetaOapg.properties.First, str, schemas.Unset] = schemas.unset,
        Prev: typing.Union[MetaOapg.properties.Prev, str, schemas.Unset] = schemas.unset,
        Next: typing.Union[MetaOapg.properties.Next, str, schemas.Unset] = schemas.unset,
        Last: typing.Union[MetaOapg.properties.Last, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Links':
        return super().__new__(
            cls,
            *args,
            First=First,
            Prev=Prev,
            Next=Next,
            Last=Last,
            _configuration=_configuration,
            **kwargs,
        )
