# coding: utf-8

"""
    Account Information API

    In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 

    The version of the OpenAPI document: 3.1.11
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hsbc_account_information_ce_python_sdk import schemas  # noqa: F401


class OBBranchAndFinancialInstitutionIdentification61(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Financial institution servicing an account for the creditor.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def SchemeName() -> typing.Type['OBExternalFinancialInstitutionIdentification4Code']:
                return OBExternalFinancialInstitutionIdentification4Code
        
            @staticmethod
            def Identification() -> typing.Type['Identification2']:
                return Identification2
        
            @staticmethod
            def Name() -> typing.Type['Name1']:
                return Name1
        
            @staticmethod
            def PostalAddress() -> typing.Type['OBPostalAddress6']:
                return OBPostalAddress6
            __annotations__ = {
                "SchemeName": SchemeName,
                "Identification": Identification,
                "Name": Name,
                "PostalAddress": PostalAddress,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SchemeName"]) -> 'OBExternalFinancialInstitutionIdentification4Code': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Identification"]) -> 'Identification2': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Name"]) -> 'Name1': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PostalAddress"]) -> 'OBPostalAddress6': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["SchemeName", "Identification", "Name", "PostalAddress", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SchemeName"]) -> typing.Union['OBExternalFinancialInstitutionIdentification4Code', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Identification"]) -> typing.Union['Identification2', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Name"]) -> typing.Union['Name1', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PostalAddress"]) -> typing.Union['OBPostalAddress6', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["SchemeName", "Identification", "Name", "PostalAddress", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        SchemeName: typing.Union['OBExternalFinancialInstitutionIdentification4Code', schemas.Unset] = schemas.unset,
        Identification: typing.Union['Identification2', schemas.Unset] = schemas.unset,
        Name: typing.Union['Name1', schemas.Unset] = schemas.unset,
        PostalAddress: typing.Union['OBPostalAddress6', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'OBBranchAndFinancialInstitutionIdentification61':
        return super().__new__(
            cls,
            *args,
            SchemeName=SchemeName,
            Identification=Identification,
            Name=Name,
            PostalAddress=PostalAddress,
            _configuration=_configuration,
            **kwargs,
        )

from hsbc_account_information_ce_python_sdk.model.identification2 import Identification2
from hsbc_account_information_ce_python_sdk.model.name1 import Name1
from hsbc_account_information_ce_python_sdk.model.ob_external_financial_institution_identification4_code import OBExternalFinancialInstitutionIdentification4Code
from hsbc_account_information_ce_python_sdk.model.ob_postal_address6 import OBPostalAddress6
