# coding: utf-8

"""
    Account Information API

    In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 

    The version of the OpenAPI document: 3.1.11
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hsbc_account_information_ce_python_sdk import schemas  # noqa: F401


class OBBalanceType1Code(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Balance type, in a coded form.
    """
    
    @schemas.classproperty
    def CLOSING_AVAILABLE(cls):
        return cls("ClosingAvailable")
    
    @schemas.classproperty
    def CLOSING_BOOKED(cls):
        return cls("ClosingBooked")
    
    @schemas.classproperty
    def EXPECTED(cls):
        return cls("Expected")
    
    @schemas.classproperty
    def FORWARD_AVAILABLE(cls):
        return cls("ForwardAvailable")
    
    @schemas.classproperty
    def INTERIM_AVAILABLE(cls):
        return cls("InterimAvailable")
    
    @schemas.classproperty
    def INTERIM_BOOKED(cls):
        return cls("InterimBooked")
    
    @schemas.classproperty
    def OPENING_AVAILABLE(cls):
        return cls("OpeningAvailable")
    
    @schemas.classproperty
    def OPENING_BOOKED(cls):
        return cls("OpeningBooked")
    
    @schemas.classproperty
    def PREVIOUSLY_CLOSED_BOOKED(cls):
        return cls("PreviouslyClosedBooked")
