# coding: utf-8

"""
    Account Information API

    In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 

    The version of the OpenAPI document: 3.1.11
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hsbc_account_information_ce_python_sdk import schemas  # noqa: F401


class OBExternalLegalStructureType1Code(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Legal standing of the party.
    """


    class MetaOapg:
        enum_value_to_name = {
            "UK.OBIE.CIC": "CIC",
            "UK.OBIE.CIO": "CIO",
            "UK.OBIE.Charity": "CHARITY",
            "UK.OBIE.CoOp": "CO_OP",
            "UK.OBIE.GeneralPartnership": "GENERAL_PARTNERSHIP",
            "UK.OBIE.Individual": "INDIVIDUAL",
            "UK.OBIE.LimitedLiabilityPartnership": "LIMITED_LIABILITY_PARTNERSHIP",
            "UK.OBIE.LimitedPartnership": "LIMITED_PARTNERSHIP",
            "UK.OBIE.PrivateLimitedCompany": "PRIVATE_LIMITED_COMPANY",
            "UK.OBIE.PublicLimitedCompany": "PUBLIC_LIMITED_COMPANY",
            "UK.OBIE.ScottishLimitedPartnership": "SCOTTISH_LIMITED_PARTNERSHIP",
            "UK.OBIE.Sole": "SOLE",
        }
    
    @schemas.classproperty
    def CIC(cls):
        return cls("UK.OBIE.CIC")
    
    @schemas.classproperty
    def CIO(cls):
        return cls("UK.OBIE.CIO")
    
    @schemas.classproperty
    def CHARITY(cls):
        return cls("UK.OBIE.Charity")
    
    @schemas.classproperty
    def CO_OP(cls):
        return cls("UK.OBIE.CoOp")
    
    @schemas.classproperty
    def GENERAL_PARTNERSHIP(cls):
        return cls("UK.OBIE.GeneralPartnership")
    
    @schemas.classproperty
    def INDIVIDUAL(cls):
        return cls("UK.OBIE.Individual")
    
    @schemas.classproperty
    def LIMITED_LIABILITY_PARTNERSHIP(cls):
        return cls("UK.OBIE.LimitedLiabilityPartnership")
    
    @schemas.classproperty
    def LIMITED_PARTNERSHIP(cls):
        return cls("UK.OBIE.LimitedPartnership")
    
    @schemas.classproperty
    def PRIVATE_LIMITED_COMPANY(cls):
        return cls("UK.OBIE.PrivateLimitedCompany")
    
    @schemas.classproperty
    def PUBLIC_LIMITED_COMPANY(cls):
        return cls("UK.OBIE.PublicLimitedCompany")
    
    @schemas.classproperty
    def SCOTTISH_LIMITED_PARTNERSHIP(cls):
        return cls("UK.OBIE.ScottishLimitedPartnership")
    
    @schemas.classproperty
    def SOLE(cls):
        return cls("UK.OBIE.Sole")
