# coding: utf-8

"""
    Account Information API

    In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 

    The version of the OpenAPI document: 3.1.11
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from hsbc_account_information_ce_python_sdk import schemas  # noqa: F401


class OBParty2AddressItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Postal address of a party.
    """


    class MetaOapg:
        required = {
            "Country",
        }
        
        class properties:
        
            @staticmethod
            def Country() -> typing.Type['CountryCode']:
                return CountryCode
        
            @staticmethod
            def AddressType() -> typing.Type['OBAddressTypeCode']:
                return OBAddressTypeCode
        
            @staticmethod
            def AddressLine() -> typing.Type['OBParty2AddressItemAddressLine']:
                return OBParty2AddressItemAddressLine
        
            @staticmethod
            def StreetName() -> typing.Type['StreetName']:
                return StreetName
        
            @staticmethod
            def BuildingNumber() -> typing.Type['BuildingNumber']:
                return BuildingNumber
        
            @staticmethod
            def PostCode() -> typing.Type['PostCode']:
                return PostCode
        
            @staticmethod
            def TownName() -> typing.Type['TownName']:
                return TownName
        
            @staticmethod
            def CountrySubDivision() -> typing.Type['CountrySubDivision']:
                return CountrySubDivision
            __annotations__ = {
                "Country": Country,
                "AddressType": AddressType,
                "AddressLine": AddressLine,
                "StreetName": StreetName,
                "BuildingNumber": BuildingNumber,
                "PostCode": PostCode,
                "TownName": TownName,
                "CountrySubDivision": CountrySubDivision,
            }
    
    Country: 'CountryCode'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Country"]) -> 'CountryCode': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["AddressType"]) -> 'OBAddressTypeCode': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["AddressLine"]) -> 'OBParty2AddressItemAddressLine': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["StreetName"]) -> 'StreetName': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["BuildingNumber"]) -> 'BuildingNumber': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PostCode"]) -> 'PostCode': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["TownName"]) -> 'TownName': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["CountrySubDivision"]) -> 'CountrySubDivision': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Country", "AddressType", "AddressLine", "StreetName", "BuildingNumber", "PostCode", "TownName", "CountrySubDivision", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Country"]) -> 'CountryCode': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["AddressType"]) -> typing.Union['OBAddressTypeCode', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["AddressLine"]) -> typing.Union['OBParty2AddressItemAddressLine', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["StreetName"]) -> typing.Union['StreetName', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["BuildingNumber"]) -> typing.Union['BuildingNumber', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PostCode"]) -> typing.Union['PostCode', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["TownName"]) -> typing.Union['TownName', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["CountrySubDivision"]) -> typing.Union['CountrySubDivision', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Country", "AddressType", "AddressLine", "StreetName", "BuildingNumber", "PostCode", "TownName", "CountrySubDivision", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        Country: 'CountryCode',
        AddressType: typing.Union['OBAddressTypeCode', schemas.Unset] = schemas.unset,
        AddressLine: typing.Union['OBParty2AddressItemAddressLine', schemas.Unset] = schemas.unset,
        StreetName: typing.Union['StreetName', schemas.Unset] = schemas.unset,
        BuildingNumber: typing.Union['BuildingNumber', schemas.Unset] = schemas.unset,
        PostCode: typing.Union['PostCode', schemas.Unset] = schemas.unset,
        TownName: typing.Union['TownName', schemas.Unset] = schemas.unset,
        CountrySubDivision: typing.Union['CountrySubDivision', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'OBParty2AddressItem':
        return super().__new__(
            cls,
            *args,
            Country=Country,
            AddressType=AddressType,
            AddressLine=AddressLine,
            StreetName=StreetName,
            BuildingNumber=BuildingNumber,
            PostCode=PostCode,
            TownName=TownName,
            CountrySubDivision=CountrySubDivision,
            _configuration=_configuration,
            **kwargs,
        )

from hsbc_account_information_ce_python_sdk.model.building_number import BuildingNumber
from hsbc_account_information_ce_python_sdk.model.country_code import CountryCode
from hsbc_account_information_ce_python_sdk.model.country_sub_division import CountrySubDivision
from hsbc_account_information_ce_python_sdk.model.ob_address_type_code import OBAddressTypeCode
from hsbc_account_information_ce_python_sdk.model.ob_party2_address_item_address_line import OBParty2AddressItemAddressLine
from hsbc_account_information_ce_python_sdk.model.post_code import PostCode
from hsbc_account_information_ce_python_sdk.model.street_name import StreetName
from hsbc_account_information_ce_python_sdk.model.town_name import TownName
